#!/usr/bin/env python

import sys

def test(nbstudy):
    if nbstudy == 1:
        print("MEDStudy nb.01 execfile <uMesh2D.py>")
        print("----------------------------------->")
        execfile("uMesh2D.py")
        print("----------------------------------->")
        print("MEDStudy nb.01 end.")
        return
    else:
	snb = str(nbstudy)
        print(str(nbstudy))
        msg = ("ERRORE: studio " + snb + " non presente !!!")
        print(msg)
        return

if len(sys.argv) == 3:
    if sys.argv[1]=="test":
        print("Testing ...")
	test(int(sys.argv[2]))
    else:
        print "ERRORE: comando <",sys.argv[1],"> non disponibile !!!"
else:
    print("ERRORE: devi dare due argomenti")
    

